# access an undefined name
print a; # output: ()


# redefine
def: b is: 1;
print b; # output: 1
def: b is: 2;
print b; # output: 2


# local scope shadows an outer scope
def: a is: 1;
print a; # output: 1
{
    def: a is: 2;
    print a; # output: 2
};
print a; # output: 1


# define multiple names
def: c, d is: 3, 4;
print c; # output: 3
print d; # output: 4


# evaluate value
def: e is: 1 + 2;
print e; # output: 3
