# access an undefined name
print a # output: ()

# redefine
def: b is: 1
print b # output: 1
def: b is: 2
print b # output: 2

# local scope shadows an outer scope
def: a is: 3
print a # output: 3
{
    def: a is: 4
    print a # output: 4
}
print a # output: 3

# define multiple names
def: c, d is: 5, 6
print c # output: 5
print d # output: 6

# evaluate value
def: e is: 3 + 4
print e # output: 7

# define function
#def: f g is: g + g
#print f 3 # --output: 6

#define multi-arg function
#def: f (g, h) is: g + h
#print f (2, 3) # --output: 5

#define multiple functions
#def: f g, h (i, j) is: (g + 7, i + j)
#print f 2 # --output: 9
#print h (3, 4) # --output: 7
